-- PostgreSQL SELF JOIN demonstration:
-- hierarchical employee-manager relationships.
--
-- The key design is:
--
--   employee.manager_id REFERENCES organization.employee(employee_id)
--
-- The employee table therefore references itself. A SELF JOIN gives the
-- same table two logical roles:
--
--   employee = person being reported
--   manager  = person responsible for that employee
--
-- This script is intentionally PostgreSQL-compatible and uses database
-- constraints to protect the hierarchy.

DROP SCHEMA IF EXISTS organization CASCADE;

CREATE SCHEMA organization;

SET search_path TO organization, public;

CREATE TABLE employee (
    employee_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name    TEXT NOT NULL,
    job_title        TEXT NOT NULL,
    manager_id       BIGINT NULL,
    department       TEXT NOT NULL,
    annual_salary    NUMERIC(12, 2) NOT NULL,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT employee_name_not_blank
        CHECK (btrim(employee_name) <> ''),

    CONSTRAINT employee_title_not_blank
        CHECK (btrim(job_title) <> ''),

    CONSTRAINT employee_department_not_blank
        CHECK (btrim(department) <> ''),

    CONSTRAINT employee_salary_nonnegative
        CHECK (annual_salary >= 0),

    CONSTRAINT employee_cannot_manage_self
        CHECK (manager_id IS NULL OR manager_id <> employee_id),

    CONSTRAINT employee_manager_fk
        FOREIGN KEY (manager_id)
        REFERENCES employee(employee_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

-- This index makes direct-report lookups efficient:
--
--   WHERE manager_id = ?
--
-- It is the database-level equivalent of maintaining a child lookup
-- structure for the hierarchy.
CREATE INDEX idx_employee_manager_id
    ON employee(manager_id);

CREATE INDEX idx_employee_department_manager
    ON employee(department, manager_id);

INSERT INTO employee
    (employee_id, employee_name, job_title, manager_id, department, annual_salary)
VALUES
    (1,  'Anita',  'Chief Executive Officer', NULL, 'Executive',   220000),
    (2,  'Rahul',  'VP Engineering',          1,    'Engineering', 170000),
    (3,  'Meera',  'VP Operations',           1,    'Operations',   165000),
    (4,  'Vikram', 'Engineering Manager',     2,    'Engineering', 125000),
    (5,  'Priya',  'Engineering Manager',     2,    'Engineering', 128000),
    (6,  'Daniel', 'Operations Manager',      3,    'Operations',   120000),
    (7,  'Arjun',  'Senior Engineer',         4,    'Engineering', 105000),
    (8,  'Sana',   'Software Engineer',       4,    'Engineering',  90000),
    (9,  'Karan',  'Software Engineer',       5,    'Engineering',  92000),
    (10, 'Leena',  'Software Engineer',       5,    'Engineering',  94000),
    (11, 'Rohit',  'Operations Analyst',      6,    'Operations',    76000),
    (12, 'Neha',   'Operations Analyst',      6,    'Operations',    78000),
    (13, 'Ishaan', 'Intern',                  7,    'Engineering',  30000);

-- -------------------------------------------------------------------------
-- Immediate employee-manager SELF JOIN
-- -------------------------------------------------------------------------
--
-- INNER JOIN excludes root employees because their manager_id is NULL.
-- Two aliases are essential because employee and manager are two logical
-- roles played by rows in the same physical table.

SELECT
    e.employee_id,
    e.employee_name AS employee,
    e.job_title AS employee_title,
    m.employee_id AS manager_id,
    m.employee_name AS manager,
    m.job_title AS manager_title
FROM employee AS e
JOIN employee AS m
    ON e.manager_id = m.employee_id
ORDER BY e.employee_id;

-- -------------------------------------------------------------------------
-- LEFT SELF JOIN including organization roots
-- -------------------------------------------------------------------------
--
-- LEFT JOIN preserves employees whose manager_id is NULL.

SELECT
    e.employee_id,
    e.employee_name AS employee,
    e.job_title,
    COALESCE(m.employee_name, 'Organization Root') AS manager
FROM employee AS e
LEFT JOIN employee AS m
    ON e.manager_id = m.employee_id
ORDER BY e.employee_id;

-- -------------------------------------------------------------------------
-- Direct reports of one manager
-- -------------------------------------------------------------------------

SELECT
    employee_id,
    employee_name,
    job_title,
    department
FROM employee
WHERE manager_id = 5
ORDER BY employee_name;

-- -------------------------------------------------------------------------
-- Employees earning less than their immediate manager
-- -------------------------------------------------------------------------
--
-- The second copy of employee supplies salary information for the manager.

SELECT
    e.employee_name AS employee,
    e.annual_salary AS employee_salary,
    m.employee_name AS manager,
    m.annual_salary AS manager_salary,
    m.annual_salary - e.annual_salary AS salary_gap
FROM employee AS e
JOIN employee AS m
    ON e.manager_id = m.employee_id
WHERE e.annual_salary < m.annual_salary
ORDER BY salary_gap DESC;

-- -------------------------------------------------------------------------
-- Managers with the number of direct reports
-- -------------------------------------------------------------------------

SELECT
    m.employee_id AS manager_id,
    m.employee_name AS manager,
    COUNT(e.employee_id) AS direct_report_count
FROM employee AS m
LEFT JOIN employee AS e
    ON e.manager_id = m.employee_id
GROUP BY
    m.employee_id,
    m.employee_name
HAVING COUNT(e.employee_id) > 0
ORDER BY direct_report_count DESC, manager;

-- -------------------------------------------------------------------------
-- Employees and their management depth
-- -------------------------------------------------------------------------
--
-- Recursive CTEs are used when the requirement is more than an immediate
-- SELF JOIN. The recursive query follows manager_id repeatedly until a root
-- is reached.

WITH RECURSIVE management_chain AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        0 AS depth
    FROM employee
    WHERE manager_id IS NULL

    UNION ALL

    SELECT
        child.employee_id,
        child.employee_name,
        child.manager_id,
        parent.depth + 1
    FROM employee AS child
    JOIN management_chain AS parent
        ON child.manager_id = parent.employee_id
)
SELECT
    employee_id,
    employee_name,
    depth
FROM management_chain
ORDER BY depth, employee_id;

-- -------------------------------------------------------------------------
-- Full management path for every employee
-- -------------------------------------------------------------------------
--
-- ARRAY is used to preserve the path from root to employee.

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        0 AS depth,
        ARRAY[employee_name]::TEXT[] AS management_path
    FROM employee
    WHERE manager_id IS NULL

    UNION ALL

    SELECT
        child.employee_id,
        child.employee_name,
        child.manager_id,
        parent.depth + 1,
        parent.management_path || child.employee_name
    FROM employee AS child
    JOIN hierarchy AS parent
        ON child.manager_id = parent.employee_id
)
SELECT
    employee_id,
    employee_name,
    depth,
    array_to_string(management_path, ' -> ') AS management_path
FROM hierarchy
ORDER BY management_path;

-- -------------------------------------------------------------------------
-- Engineering employees with immediate manager information
-- -------------------------------------------------------------------------

SELECT
    e.employee_name AS employee,
    e.job_title,
    m.employee_name AS manager,
    m.job_title AS manager_title
FROM employee AS e
LEFT JOIN employee AS m
    ON e.manager_id = m.employee_id
WHERE e.department = 'Engineering'
ORDER BY e.employee_name;

-- -------------------------------------------------------------------------
-- Find employees who report to managers in another department
-- -------------------------------------------------------------------------

SELECT
    e.employee_name AS employee,
    e.department AS employee_department,
    m.employee_name AS manager,
    m.department AS manager_department
FROM employee AS e
JOIN employee AS m
    ON e.manager_id = m.employee_id
WHERE e.department <> m.department
ORDER BY e.employee_name;

-- -------------------------------------------------------------------------
-- Demonstrate a transaction for a hierarchy change
-- -------------------------------------------------------------------------
--
-- Sana moves from Vikram (4) to Priya (5).
--
-- The foreign key guarantees that manager 5 exists. The self-management
-- CHECK prevents manager_id = employee_id. Application-level cycle
-- detection is still necessary for multi-row hierarchical cycles because
-- ordinary foreign keys do not by themselves prove that the graph is acyclic.

BEGIN;

UPDATE employee
SET manager_id = 5
WHERE employee_id = 8;

-- Verify the resulting immediate relationship before committing.

SELECT
    e.employee_name AS employee,
    m.employee_name AS manager
FROM employee AS e
LEFT JOIN employee AS m
    ON e.manager_id = m.employee_id
WHERE e.employee_id = 8;

COMMIT;

-- -------------------------------------------------------------------------
-- Invalid direct self-management is rejected by the CHECK constraint.
-- This statement is intentionally isolated inside a savepoint so the
-- demonstration does not terminate the remainder of the SQL script.
-- -------------------------------------------------------------------------

BEGIN;

SAVEPOINT invalid_self_manager;

UPDATE employee
SET manager_id = employee_id
WHERE employee_id = 5;

ROLLBACK TO SAVEPOINT invalid_self_manager;

COMMIT;

-- -------------------------------------------------------------------------
-- Invalid manager references are rejected by the foreign key.
-- -------------------------------------------------------------------------

BEGIN;

SAVEPOINT invalid_manager_reference;

UPDATE employee
SET manager_id = 999999
WHERE employee_id = 8;

ROLLBACK TO SAVEPOINT invalid_manager_reference;

COMMIT;

-- -------------------------------------------------------------------------
-- Managers at each hierarchy level
-- -------------------------------------------------------------------------

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        0 AS depth
    FROM employee
    WHERE manager_id IS NULL

    UNION ALL

    SELECT
        e.employee_id,
        e.employee_name,
        e.manager_id,
        h.depth + 1
    FROM employee AS e
    JOIN hierarchy AS h
        ON e.manager_id = h.employee_id
)
SELECT
    depth,
    COUNT(*) AS employee_count
FROM hierarchy
GROUP BY depth
ORDER BY depth;

-- -------------------------------------------------------------------------
-- Employees with at least two levels of management above them
-- -------------------------------------------------------------------------

WITH RECURSIVE hierarchy AS (
    SELECT
        employee_id,
        employee_name,
        manager_id,
        0 AS depth
    FROM employee
    WHERE manager_id IS NULL

    UNION ALL

    SELECT
        e.employee_id,
        e.employee_name,
        e.manager_id,
        h.depth + 1
    FROM employee AS e
    JOIN hierarchy AS h
        ON e.manager_id = h.employee_id
)
SELECT
    employee_id,
    employee_name,
    depth
FROM hierarchy
WHERE depth >= 2
ORDER BY depth, employee_name;

-- -------------------------------------------------------------------------
-- Practical view for repeated employee-manager reporting
-- -------------------------------------------------------------------------

CREATE OR REPLACE VIEW employee_manager_view AS
SELECT
    e.employee_id,
    e.employee_name AS employee_name,
    e.job_title AS employee_title,
    e.department,
    e.annual_salary,
    e.manager_id,
    m.employee_name AS manager_name,
    m.job_title AS manager_title
FROM employee AS e
LEFT JOIN employee AS m
    ON e.manager_id = m.employee_id;

SELECT *
FROM employee_manager_view
ORDER BY employee_id;

-- -------------------------------------------------------------------------
-- Hierarchical integrity checks
-- -------------------------------------------------------------------------
--
-- Missing managers cannot exist because of the foreign key, but this query
-- demonstrates the logical condition that should be monitored in imported
-- or staged data.

SELECT
    e.employee_id,
    e.employee_name,
    e.manager_id
FROM employee AS e
LEFT JOIN employee AS m
    ON e.manager_id = m.employee_id
WHERE e.manager_id IS NOT NULL
  AND m.employee_id IS NULL;

-- Root employees are the rows with no parent.

SELECT
    employee_id,
    employee_name,
    job_title
FROM employee
WHERE manager_id IS NULL
ORDER BY employee_id;

-- -------------------------------------------------------------------------
-- Explain why the manager index matters for SELF JOIN workloads
-- -------------------------------------------------------------------------

EXPLAIN
SELECT
    e.employee_name,
    m.employee_name AS manager
FROM employee AS e
JOIN employee AS m
    ON e.manager_id = m.employee_id
WHERE e.manager_id = 5;
